name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2     
      - name: Disable Host Key Verification
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
      - name: Configure SSH environment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy to remote machine
        run: |
          pwd
          ls -l
          # Replace remote-user and remote-host with your SSH credentials         
          scp -r $GITHUB_WORKSPACE/* github@195.35.23.133:/opt/pdfpython/app
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: 195.35.23.133
          username: github
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ''
          script: |
            cd /opt/pdfpython/app
            pm2 reload all
